# Use root/password1 as user/password credentials
version: '3.1'

services:

  mongodb_container:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    container_name: db_mongo
    volumes:
      - ./mongo/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password1