version: '1'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'wartagkjmedari_api'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'pass@word1'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'Pass@word1'
      # Timezone
      TZ: Asia/Jakarta
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./mysql:/var/lib/mysql